package com.riskcalc.mobile.ui.theme

import androidx.compose.ui.graphics.Color

val CareCoral = Color(0xFFB62D23)
val OnCareCoral = Color(0xFFFFFFFF)
val CareCoralContainer = Color(0xFFFFDAD4)
val OnCareCoralContainer = Color(0xFF3F0301)
val CalmSage = Color(0xFF48624D)
val OnCalmSage = Color(0xFFFFFFFF)
val CalmSageContainer = Color(0xFFCBE8CF)
val OnCalmSageContainer = Color(0xFF06210D)
val WarmGold = Color(0xFF705D00)
val OnWarmGold = Color(0xFFFFFFFF)
val WarmGoldContainer = Color(0xFFFFE16D)
val OnWarmGoldContainer = Color(0xFF221B00)
val CareBackground = Color(0xFFFFF3EC)
val CareSurface = Color(0xFFFFF9F6)
val CareSurfaceContainer = Color(0xFFF8E8E0)
val CareOnSurface = Color(0xFF241A17)
val CareOutline = Color(0xFF8D716A)

val DarkCareCoral = Color(0xFFFFB4A9)
val DarkOnCareCoral = Color(0xFF680E08)
val DarkCareCoralContainer = Color(0xFF912018)
val DarkOnCareCoralContainer = Color(0xFFFFDAD4)
val DarkCalmSage = Color(0xFFAFD0B4)
val DarkOnCalmSage = Color(0xFF1A3520)
val DarkCalmSageContainer = Color(0xFF314A36)
val DarkOnCalmSageContainer = Color(0xFFCBE8CF)
val DarkWarmGold = Color(0xFFE5C53B)
val DarkOnWarmGold = Color(0xFF3A3000)
val DarkWarmGoldContainer = Color(0xFF554700)
val DarkOnWarmGoldContainer = Color(0xFFFFE16D)
val DarkCareBackground = Color(0xFF171210)
val DarkCareSurface = Color(0xFF1D1816)
val DarkCareSurfaceContainer = Color(0xFF2A211E)
val DarkCareOnSurface = Color(0xFFF4DED8)
val DarkCareOutline = Color(0xFFAA8B83)
